# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alex/Documents/Code/vela

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alex/Documents/Code/vela

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/Documents/Code/vela/CMakeFiles /Users/alex/Documents/Code/vela//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/Documents/Code/vela/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vela

# Build rule for target.
vela: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vela
.PHONY : vela

# fast build rule for target.
vela/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/build
.PHONY : vela/fast

#=============================================================================
# Target rules for targets named vela-velf

# Build rule for target.
vela-velf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vela-velf
.PHONY : vela-velf

# fast build rule for target.
vela-velf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela-velf.dir/build.make CMakeFiles/vela-velf.dir/build
.PHONY : vela-velf/fast

#=============================================================================
# Target rules for targets named vela.self-self

# Build rule for target.
vela.self-self: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vela.self-self
.PHONY : vela.self-self

# fast build rule for target.
vela.self-self/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.self-self.dir/build.make CMakeFiles/vela.self-self.dir/build
.PHONY : vela.self-self/fast

#=============================================================================
# Target rules for targets named vela.vpk-vpk

# Build rule for target.
vela.vpk-vpk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vela.vpk-vpk
.PHONY : vela.vpk-vpk

# fast build rule for target.
vela.vpk-vpk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.vpk-vpk.dir/build.make CMakeFiles/vela.vpk-vpk.dir/build
.PHONY : vela.vpk-vpk/fast

src/app.obj: src/app.cpp.obj
.PHONY : src/app.obj

# target to build an object file
src/app.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/app.cpp.obj
.PHONY : src/app.cpp.obj

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/camera.obj: src/camera.cpp.obj
.PHONY : src/camera.obj

# target to build an object file
src/camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/camera.cpp.obj
.PHONY : src/camera.cpp.obj

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/image_utils.obj: src/image_utils.cpp.obj
.PHONY : src/image_utils.obj

# target to build an object file
src/image_utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/image_utils.cpp.obj
.PHONY : src/image_utils.cpp.obj

src/image_utils.i: src/image_utils.cpp.i
.PHONY : src/image_utils.i

# target to preprocess a source file
src/image_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/image_utils.cpp.i
.PHONY : src/image_utils.cpp.i

src/image_utils.s: src/image_utils.cpp.s
.PHONY : src/image_utils.s

# target to generate assembly for a file
src/image_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/image_utils.cpp.s
.PHONY : src/image_utils.cpp.s

src/input.obj: src/input.cpp.obj
.PHONY : src/input.obj

# target to build an object file
src/input.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/input.cpp.obj
.PHONY : src/input.cpp.obj

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/keyboard.obj: src/keyboard.cpp.obj
.PHONY : src/keyboard.obj

# target to build an object file
src/keyboard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/keyboard.cpp.obj
.PHONY : src/keyboard.cpp.obj

src/keyboard.i: src/keyboard.cpp.i
.PHONY : src/keyboard.i

# target to preprocess a source file
src/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/keyboard.cpp.i
.PHONY : src/keyboard.cpp.i

src/keyboard.s: src/keyboard.cpp.s
.PHONY : src/keyboard.s

# target to generate assembly for a file
src/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/keyboard.cpp.s
.PHONY : src/keyboard.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net.obj: src/net.cpp.obj
.PHONY : src/net.obj

# target to build an object file
src/net.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/net.cpp.obj
.PHONY : src/net.cpp.obj

src/net.i: src/net.cpp.i
.PHONY : src/net.i

# target to preprocess a source file
src/net.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/net.cpp.i
.PHONY : src/net.cpp.i

src/net.s: src/net.cpp.s
.PHONY : src/net.s

# target to generate assembly for a file
src/net.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/net.cpp.s
.PHONY : src/net.cpp.s

src/persistence.obj: src/persistence.cpp.obj
.PHONY : src/persistence.obj

# target to build an object file
src/persistence.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/persistence.cpp.obj
.PHONY : src/persistence.cpp.obj

src/persistence.i: src/persistence.cpp.i
.PHONY : src/persistence.i

# target to preprocess a source file
src/persistence.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/persistence.cpp.i
.PHONY : src/persistence.cpp.i

src/persistence.s: src/persistence.cpp.s
.PHONY : src/persistence.s

# target to generate assembly for a file
src/persistence.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/persistence.cpp.s
.PHONY : src/persistence.cpp.s

src/sessions.obj: src/sessions.cpp.obj
.PHONY : src/sessions.obj

# target to build an object file
src/sessions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/sessions.cpp.obj
.PHONY : src/sessions.cpp.obj

src/sessions.i: src/sessions.cpp.i
.PHONY : src/sessions.i

# target to preprocess a source file
src/sessions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/sessions.cpp.i
.PHONY : src/sessions.cpp.i

src/sessions.s: src/sessions.cpp.s
.PHONY : src/sessions.s

# target to generate assembly for a file
src/sessions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/sessions.cpp.s
.PHONY : src/sessions.cpp.s

src/settings.obj: src/settings.cpp.obj
.PHONY : src/settings.obj

# target to build an object file
src/settings.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/settings.cpp.obj
.PHONY : src/settings.cpp.obj

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/ui.obj: src/ui.cpp.obj
.PHONY : src/ui.obj

# target to build an object file
src/ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/ui.cpp.obj
.PHONY : src/ui.cpp.obj

src/ui.i: src/ui.cpp.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vela.dir/build.make CMakeFiles/vela.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vela-velf"
	@echo "... vela.self-self"
	@echo "... vela.vpk-vpk"
	@echo "... vela"
	@echo "... src/app.obj"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/camera.obj"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/image_utils.obj"
	@echo "... src/image_utils.i"
	@echo "... src/image_utils.s"
	@echo "... src/input.obj"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/keyboard.obj"
	@echo "... src/keyboard.i"
	@echo "... src/keyboard.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net.obj"
	@echo "... src/net.i"
	@echo "... src/net.s"
	@echo "... src/persistence.obj"
	@echo "... src/persistence.i"
	@echo "... src/persistence.s"
	@echo "... src/sessions.obj"
	@echo "... src/sessions.i"
	@echo "... src/sessions.s"
	@echo "... src/settings.obj"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/ui.obj"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

